import { CategoryEnum, type CategoryData } from "./types";

export const commandMenuData: CategoryData = {
  [CategoryEnum.DASHBOARD]: [
    // Navigation
    {
      slug: "dashboard-home",
      url: "/dashboard",
      group: { key: "navigation", name: "Navigation" },
      content: "Dashboard Home",
      category: CategoryEnum.DASHBOARD,
      type: "navigation",
      icon: "solar:home-2-linear",
      description: "Main dashboard overview",
      keywords: ["home", "overview", "main"],
    },
    // Actions
    {
      slug: "switch-to-news",
      url: "/news/dashboard",
      group: { key: "actions", name: "Quick Actions" },
      content: "Switch to News App",
      category: CategoryEnum.DASHBOARD,
      type: "action",
      icon: "solar:document-text-linear",
      description: "Navigate to news application",
      keywords: ["news", "articles", "switch"],
    },
    {
      slug: "switch-to-tasks",
      url: "/task-management/dashboard",
      group: { key: "actions", name: "Quick Actions" },
      content: "Switch to Task Management",
      category: CategoryEnum.DASHBOARD,
      type: "action",
      icon: "solar:checklist-minimalistic-linear",
      description: "Navigate to task management",
      keywords: ["tasks", "projects", "switch"],
    },
    {
      slug: "switch-to-time",
      url: "/time-management/dashboard",
      group: { key: "actions", name: "Quick Actions" },
      content: "Switch to Time Management",
      category: CategoryEnum.DASHBOARD,
      type: "action",
      icon: "solar:clock-circle-linear",
      description: "Navigate to time tracking",
      keywords: ["time", "tracking", "switch"],
    },
  ],

  [CategoryEnum.NEWS]: [
    // Navigation
    {
      slug: "news-dashboard",
      url: "/news/dashboard",
      group: { key: "navigation", name: "Navigation" },
      content: "News Dashboard",
      category: CategoryEnum.NEWS,
      type: "navigation",
      icon: "solar:home-2-linear",
      description: "News application overview",
      keywords: ["dashboard", "overview"],
    },
    {
      slug: "articles",
      url: "/news/articles",
      group: { key: "navigation", name: "Navigation" },
      content: "Articles",
      category: CategoryEnum.NEWS,
      type: "navigation",
      icon: "solar:document-text-linear",
      description: "Browse and manage articles",
      keywords: ["articles", "posts", "content"],
    },
    {
      slug: "categories",
      url: "/news/categories",
      group: { key: "navigation", name: "Navigation" },
      content: "Categories",
      category: CategoryEnum.NEWS,
      type: "navigation",
      icon: "solar:folder-linear",
      description: "Manage article categories",
      keywords: ["categories", "tags", "organize"],
    },
    {
      slug: "trending",
      url: "/news/trending",
      group: { key: "navigation", name: "Navigation" },
      content: "Trending",
      category: CategoryEnum.NEWS,
      type: "navigation",
      icon: "solar:fire-linear",
      description: "View trending articles",
      keywords: ["trending", "popular", "hot"],
    },
    // Actions
    {
      slug: "create-article",
      url: "/news/articles/create",
      group: { key: "actions", name: "Quick Actions" },
      content: "Create New Article",
      category: CategoryEnum.NEWS,
      type: "action",
      icon: "solar:add-circle-linear",
      description: "Write a new article",
      keywords: ["create", "new", "write", "article"],
    },
    {
      slug: "manage-categories",
      url: "/news/categories/manage",
      group: { key: "actions", name: "Quick Actions" },
      content: "Manage Categories",
      category: CategoryEnum.NEWS,
      type: "action",
      icon: "solar:settings-linear",
      description: "Add or edit categories",
      keywords: ["manage", "categories", "settings"],
    },
  ],

  [CategoryEnum.TASKS]: [
    // Navigation
    {
      slug: "task-dashboard",
      url: "/task-management/dashboard",
      group: { key: "navigation", name: "Navigation" },
      content: "Task Dashboard",
      category: CategoryEnum.TASKS,
      type: "navigation",
      icon: "solar:home-2-linear",
      description: "Task management overview",
      keywords: ["dashboard", "overview"],
    },
    {
      slug: "tasks-list",
      url: "/task-management/tasks",
      group: { key: "navigation", name: "Navigation" },
      content: "Tasks",
      category: CategoryEnum.TASKS,
      type: "navigation",
      icon: "solar:checklist-minimalistic-linear",
      description: "View and manage tasks",
      keywords: ["tasks", "todo", "list"],
    },
    {
      slug: "projects",
      url: "/task-management/projects",
      group: { key: "navigation", name: "Navigation" },
      content: "Projects",
      category: CategoryEnum.TASKS,
      type: "navigation",
      icon: "solar:widget-2-linear",
      description: "Manage projects",
      keywords: ["projects", "workspace"],
    },
    {
      slug: "team",
      url: "/task-management/team",
      group: { key: "navigation", name: "Navigation" },
      content: "Team",
      category: CategoryEnum.TASKS,
      type: "navigation",
      icon: "solar:users-group-two-rounded-linear",
      description: "Team collaboration",
      keywords: ["team", "members", "collaboration"],
    },
    {
      slug: "calendar",
      url: "/task-management/calendar",
      group: { key: "navigation", name: "Navigation" },
      content: "Calendar",
      category: CategoryEnum.TASKS,
      type: "navigation",
      icon: "solar:calendar-linear",
      description: "Task calendar view",
      keywords: ["calendar", "schedule", "timeline"],
    },
    // Actions
    {
      slug: "create-task",
      url: "/task-management/create-task",
      group: { key: "actions", name: "Quick Actions" },
      content: "Create New Task",
      category: CategoryEnum.TASKS,
      type: "action",
      icon: "solar:add-circle-linear",
      description: "Add a new task",
      keywords: ["create", "new", "task", "add"],
      isNew: true,
    },
    {
      slug: "create-project",
      url: "/task-management/projects/create",
      group: { key: "actions", name: "Quick Actions" },
      content: "Create New Project",
      category: CategoryEnum.TASKS,
      type: "action",
      icon: "solar:widget-add-linear",
      description: "Start a new project",
      keywords: ["create", "new", "project"],
    },
  ],

  [CategoryEnum.TIME]: [
    // Navigation
    {
      slug: "time-dashboard",
      url: "/time-management/dashboard",
      group: { key: "navigation", name: "Navigation" },
      content: "Time Dashboard",
      category: CategoryEnum.TIME,
      type: "navigation",
      icon: "solar:home-2-linear",
      description: "Time management overview",
      keywords: ["dashboard", "overview"],
    },
    {
      slug: "time-tracking",
      url: "/time-management/tracking",
      group: { key: "navigation", name: "Navigation" },
      content: "Time Tracking",
      category: CategoryEnum.TIME,
      type: "navigation",
      icon: "solar:stopwatch-linear",
      description: "Track your time",
      keywords: ["tracking", "timer", "stopwatch"],
    },
    {
      slug: "reports",
      url: "/time-management/reports",
      group: { key: "navigation", name: "Navigation" },
      content: "Reports",
      category: CategoryEnum.TIME,
      type: "navigation",
      icon: "solar:chart-linear",
      description: "View time reports",
      keywords: ["reports", "analytics", "statistics"],
    },
    {
      slug: "time-calendar",
      url: "/time-management/calendar",
      group: { key: "navigation", name: "Navigation" },
      content: "Calendar",
      category: CategoryEnum.TIME,
      type: "navigation",
      icon: "solar:calendar-linear",
      description: "Time calendar view",
      keywords: ["calendar", "schedule"],
    },
    // Actions
    {
      slug: "start-timer",
      url: "/time-management/tracking?action=start",
      group: { key: "actions", name: "Quick Actions" },
      content: "Start Timer",
      category: CategoryEnum.TIME,
      type: "action",
      icon: "solar:play-circle-linear",
      description: "Start tracking time",
      keywords: ["start", "timer", "track"],
    },
    {
      slug: "create-time-entry",
      url: "/time-management/tracking/create",
      group: { key: "actions", name: "Quick Actions" },
      content: "Create Time Entry",
      category: CategoryEnum.TIME,
      type: "action",
      icon: "solar:add-circle-linear",
      description: "Add manual time entry",
      keywords: ["create", "entry", "manual"],
    },
  ],
};
